-- AlterTable
ALTER TABLE `order` ADD COLUMN `trackingNumber` VARCHAR(191) NULL,
    MODIFY `status` ENUM('PENDING', 'PAID', 'IN_DELIVERY', 'COMPLETED', 'FAILED', 'CANCELED') NOT NULL DEFAULT 'PENDING';
